### PR TITLE
Upgrade gazelle to 0.22.2 and rules_go to 0.25.0

### PR DESCRIPTION
**Pull request by KarolisL**

### CODE REVIEW

**Comment by asv** [comment]
@ jmhodges review & merge, please. This PR block migration to rules_go 0.25.0

**Comment by lukedirtwalker** [comment]
You can also remove the `go_rule` import in https://github.com/jmhodges/bazel_gomock/pull/49/files#diff-d24e74c654eb03cfb63ed6a3c711b12aa694a0f36f36fab7a83563a6c14f4042L1

**Comment by EdSchouten** [comment]
Friendly ping!

**Comment by jmhodges** [comment]
Thanks!

**Pull request merged**
